# Generated by Django 3.1.1 on 2020-09-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counternumber',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.speciesmodel'),
        ),
    ]
