# Generated by Django 3.1.1 on 2020-09-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_counternumber_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemtemName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Oree'), ('2', 'Babawa')], max_length=200)),
            ],
        ),
    ]
