# Generated by Django 3.1.1 on 2020-09-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_temtemname_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counternumber',
            name='description',
        ),
        migrations.AddField(
            model_name='counternumber',
            name='species',
            field=models.CharField(choices=[('Oree', 'Oree'), ('Babawa', 'Babawa')], default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='temtemname',
            name='name',
            field=models.CharField(choices=[('Oree', 'Oree'), ('Babawa', 'Babawa')], max_length=200),
        ),
    ]
