# Generated by Django 3.1.1 on 2020-09-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_auto_20200917_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemtemName',
        ),
    ]
