# Generated by Django 3.1.1 on 2020-09-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0006_auto_20200928_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesmodel',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
