# Generated by Django 3.1.1 on 2020-09-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0007_speciesmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesmodel',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
